#!/bin/bash

# Verifica se o arquivo dhcpd.conf existe
if [ -f "/etc/dhcp/dhcpd.conf" ]; then
    # Copia o arquivo para o diretório atual
    cp /etc/dhcp/dhcpd.conf .
    echo "Arquivo dhcpd.conf copiado com sucesso para $(pwd)"
else
    echo "Erro: O arquivo dhcpd.conf não foi encontrado em /etc/dhcp."
    exit
fi


python3 scan
